// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9b_PGSlhm6WTnxYeGinn3oZ9hQ5wC3HA',
    appId: '1:244050365953:android:1744b1629772aa95167a00',
    messagingSenderId: '244050365953',
    projectId: 'mr-gharbeti',
    storageBucket: 'mr-gharbeti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9FXDdI03LJnSno09zwI7pfGkX5DOCgag',
    appId: '1:244050365953:ios:33262ed140d4ead0167a00',
    messagingSenderId: '244050365953',
    projectId: 'mr-gharbeti',
    storageBucket: 'mr-gharbeti.appspot.com',
    androidClientId: '244050365953-85tvjunt2o1966b5iemc4m9d9dc85k5p.apps.googleusercontent.com',
    iosClientId: '244050365953-02trqs7ujv4dgu31373gd453c3l10ojk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrGharbeti',
  );
}
